spring.application.name=central-hub
server.port=8082

logging.logstash.host=logstash
logging.logstash.port=5044

#add a local file path for local run as  below path might not work due to permission issue
#logging.file.name=/var/log/central-hub/central-hub.log
logging.file.max-size=10MB
logging.file.max-history=30