spring.application.name=central-hub
server.port=8080

logging.logstash.host=logstash
logging.logstash.port=5044

#add a local file path for local run as  below path might not work due to permission issue
#logging.file.name=/var/log/central-hub/central-hub.log
logging.file.max-size=10MB
logging.file.max-history=30

springdoc.ui.path: /swagger-ui.html
springdoc.ui.config-url: /v3/api-docs

#redis.host=redis.shopsmartsg.com
redis.host=redis.ss.gcp.local
#redis.port=6379 cant use this as this is for unencrypted connection to redis
redis.port=6378
redis.db=1
redis.password=
redis.use.ssl=true
redis.ssl.cert.path=/etc/redis/ssl/certs/redis-ca.pem

frontend_url=https://app.shopsmartsg.com

#oauth2.redirect_uri=http://localhost:8080/auth/google/callback
#oauth2.scope=openid profile email
#gcip.request_uri=http://localhost:8080

oauth2.client_id={OAUTH2_CLIENT_ID}
oauth2.client_secret={OAUTH2_CLIENT_SECRET}
oauth2.redirect_uri=https://central-hub.shopsmartsg.com/auth/google/callback
oauth2.scope=openid email
oauth2.authorization_endpoint=https://accounts.google.com/o/oauth2/v2/auth
oauth2.token_endpoint=https://oauth2.googleapis.com/token

gcip.api_key={GCIP_API_KEY}
gcip.request_uri=https://central-hub.shopsmartsg.com
gcip.sign_in_with_idp_url=https://identitytoolkit.googleapis.com/v1/accounts:signInWithIdp?key=
gcip.account_lookup_url=https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=
gcip.refresh_id_token_url=https://securetoken.googleapis.com/v1/token?key=
gcip.sign_up_native_url=https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=
gcip.login_native_url=https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=